/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiEmployeesRouteImport } from './routes/ai-employees'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as AiEmployeesSlugRouteImport } from './routes/ai-employees/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies/$slug'
import { Route as IndustriesAgenciesRouteImport } from './routes/industries/agencies'
import { Route as IndustriesBrokeragesRouteImport } from './routes/industries/brokerages'
import { Route as IndustriesBuildersRouteImport } from './routes/industries/builders'
import { Route as IndustriesChannelPartnersRouteImport } from './routes/industries/channel-partners'
import { Route as IndustriesCommercialRouteImport } from './routes/industries/commercial'
import { Route as IndustriesDevelopersRouteImport } from './routes/industries/developers'
import { Route as IndustriesLuxuryRouteImport } from './routes/industries/luxury'
import { Route as IndustriesPropertyManagementRouteImport } from './routes/industries/property-management'
import { Route as IntegrationsSlugRouteImport } from './routes/integrations/$slug'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as SolutionsSlugRouteImport } from './routes/solutions/$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog/category/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEmployeesRoute = AiEmployeesRouteImport.update({
  id: '/ai-employees',
  path: '/ai-employees',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEmployeesSlugRoute = AiEmployeesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AiEmployeesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const IndustriesAgenciesRoute = IndustriesAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesBrokeragesRoute = IndustriesBrokeragesRouteImport.update({
  id: '/brokerages',
  path: '/brokerages',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesBuildersRoute = IndustriesBuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesChannelPartnersRoute =
  IndustriesChannelPartnersRouteImport.update({
    id: '/channel-partners',
    path: '/channel-partners',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesCommercialRoute = IndustriesCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesDevelopersRoute = IndustriesDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesLuxuryRoute = IndustriesLuxuryRouteImport.update({
  id: '/luxury',
  path: '/luxury',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesPropertyManagementRoute =
  IndustriesPropertyManagementRouteImport.update({
    id: '/property-management',
    path: '/property-management',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IntegrationsSlugRoute = IntegrationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IntegrationsRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-employees': typeof AiEmployeesRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/book-demo': typeof BookDemoRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/ai-employees/$slug': typeof AiEmployeesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/agencies': typeof IndustriesAgenciesRoute
  '/industries/brokerages': typeof IndustriesBrokeragesRoute
  '/industries/builders': typeof IndustriesBuildersRoute
  '/industries/channel-partners': typeof IndustriesChannelPartnersRoute
  '/industries/commercial': typeof IndustriesCommercialRoute
  '/industries/developers': typeof IndustriesDevelopersRoute
  '/industries/luxury': typeof IndustriesLuxuryRoute
  '/industries/property-management': typeof IndustriesPropertyManagementRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-employees': typeof AiEmployeesRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/book-demo': typeof BookDemoRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/ai-employees/$slug': typeof AiEmployeesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/agencies': typeof IndustriesAgenciesRoute
  '/industries/brokerages': typeof IndustriesBrokeragesRoute
  '/industries/builders': typeof IndustriesBuildersRoute
  '/industries/channel-partners': typeof IndustriesChannelPartnersRoute
  '/industries/commercial': typeof IndustriesCommercialRoute
  '/industries/developers': typeof IndustriesDevelopersRoute
  '/industries/luxury': typeof IndustriesLuxuryRoute
  '/industries/property-management': typeof IndustriesPropertyManagementRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-employees': typeof AiEmployeesRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/book-demo': typeof BookDemoRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/ai-employees/$slug': typeof AiEmployeesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/agencies': typeof IndustriesAgenciesRoute
  '/industries/brokerages': typeof IndustriesBrokeragesRoute
  '/industries/builders': typeof IndustriesBuildersRoute
  '/industries/channel-partners': typeof IndustriesChannelPartnersRoute
  '/industries/commercial': typeof IndustriesCommercialRoute
  '/industries/developers': typeof IndustriesDevelopersRoute
  '/industries/luxury': typeof IndustriesLuxuryRoute
  '/industries/property-management': typeof IndustriesPropertyManagementRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-employees'
    | '/blog'
    | '/book-demo'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/integrations'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/sitemap.xml'
    | '/solutions'
    | '/ai-employees/$slug'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/agencies'
    | '/industries/brokerages'
    | '/industries/builders'
    | '/industries/channel-partners'
    | '/industries/commercial'
    | '/industries/developers'
    | '/industries/luxury'
    | '/industries/property-management'
    | '/integrations/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/resources/$slug'
    | '/solutions/$slug'
    | '/blog/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-employees'
    | '/blog'
    | '/book-demo'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/integrations'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/sitemap.xml'
    | '/solutions'
    | '/ai-employees/$slug'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/agencies'
    | '/industries/brokerages'
    | '/industries/builders'
    | '/industries/channel-partners'
    | '/industries/commercial'
    | '/industries/developers'
    | '/industries/luxury'
    | '/industries/property-management'
    | '/integrations/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/resources/$slug'
    | '/solutions/$slug'
    | '/blog/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-employees'
    | '/blog'
    | '/book-demo'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/integrations'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/sitemap.xml'
    | '/solutions'
    | '/ai-employees/$slug'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/agencies'
    | '/industries/brokerages'
    | '/industries/builders'
    | '/industries/channel-partners'
    | '/industries/commercial'
    | '/industries/developers'
    | '/industries/luxury'
    | '/industries/property-management'
    | '/integrations/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/resources/$slug'
    | '/solutions/$slug'
    | '/blog/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiEmployeesRoute: typeof AiEmployeesRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  BookDemoRoute: typeof BookDemoRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-employees': {
      id: '/ai-employees'
      path: '/ai-employees'
      fullPath: '/ai-employees'
      preLoaderRoute: typeof AiEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-employees/$slug': {
      id: '/ai-employees/$slug'
      path: '/$slug'
      fullPath: '/ai-employees/$slug'
      preLoaderRoute: typeof AiEmployeesSlugRouteImport
      parentRoute: typeof AiEmployeesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/industries/agencies': {
      id: '/industries/agencies'
      path: '/agencies'
      fullPath: '/industries/agencies'
      preLoaderRoute: typeof IndustriesAgenciesRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/brokerages': {
      id: '/industries/brokerages'
      path: '/brokerages'
      fullPath: '/industries/brokerages'
      preLoaderRoute: typeof IndustriesBrokeragesRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/builders': {
      id: '/industries/builders'
      path: '/builders'
      fullPath: '/industries/builders'
      preLoaderRoute: typeof IndustriesBuildersRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/channel-partners': {
      id: '/industries/channel-partners'
      path: '/channel-partners'
      fullPath: '/industries/channel-partners'
      preLoaderRoute: typeof IndustriesChannelPartnersRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/commercial': {
      id: '/industries/commercial'
      path: '/commercial'
      fullPath: '/industries/commercial'
      preLoaderRoute: typeof IndustriesCommercialRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/developers': {
      id: '/industries/developers'
      path: '/developers'
      fullPath: '/industries/developers'
      preLoaderRoute: typeof IndustriesDevelopersRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/luxury': {
      id: '/industries/luxury'
      path: '/luxury'
      fullPath: '/industries/luxury'
      preLoaderRoute: typeof IndustriesLuxuryRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/property-management': {
      id: '/industries/property-management'
      path: '/property-management'
      fullPath: '/industries/property-management'
      preLoaderRoute: typeof IndustriesPropertyManagementRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/integrations/$slug': {
      id: '/integrations/$slug'
      path: '/$slug'
      fullPath: '/integrations/$slug'
      preLoaderRoute: typeof IntegrationsSlugRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface AiEmployeesRouteChildren {
  AiEmployeesSlugRoute: typeof AiEmployeesSlugRoute
}

const AiEmployeesRouteChildren: AiEmployeesRouteChildren = {
  AiEmployeesSlugRoute: AiEmployeesSlugRoute,
}

const AiEmployeesRouteWithChildren = AiEmployeesRoute._addFileChildren(
  AiEmployeesRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface IndustriesRouteChildren {
  IndustriesAgenciesRoute: typeof IndustriesAgenciesRoute
  IndustriesBrokeragesRoute: typeof IndustriesBrokeragesRoute
  IndustriesBuildersRoute: typeof IndustriesBuildersRoute
  IndustriesChannelPartnersRoute: typeof IndustriesChannelPartnersRoute
  IndustriesCommercialRoute: typeof IndustriesCommercialRoute
  IndustriesDevelopersRoute: typeof IndustriesDevelopersRoute
  IndustriesLuxuryRoute: typeof IndustriesLuxuryRoute
  IndustriesPropertyManagementRoute: typeof IndustriesPropertyManagementRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesAgenciesRoute: IndustriesAgenciesRoute,
  IndustriesBrokeragesRoute: IndustriesBrokeragesRoute,
  IndustriesBuildersRoute: IndustriesBuildersRoute,
  IndustriesChannelPartnersRoute: IndustriesChannelPartnersRoute,
  IndustriesCommercialRoute: IndustriesCommercialRoute,
  IndustriesDevelopersRoute: IndustriesDevelopersRoute,
  IndustriesLuxuryRoute: IndustriesLuxuryRoute,
  IndustriesPropertyManagementRoute: IndustriesPropertyManagementRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface IntegrationsRouteChildren {
  IntegrationsSlugRoute: typeof IntegrationsSlugRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsSlugRoute: IntegrationsSlugRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiEmployeesRoute: AiEmployeesRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  BookDemoRoute: BookDemoRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
